# Use root/mysql as user/password credentials
version: "3.1"
services:
  db:
    container_name: invoice_db
    image: mysql:5.7.34
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: hbinvoice
      MYSQL_PASSWORD: hbinvoice
      MYSQL_DATABASE: hb_invoice_db
    ports:
      - 3394:3306
    mem_limit: 512m
    volumes:
      - mysql-invoice-mvc:/var/lib/mysql

  adminer:
    container_name: invoice_db_admin
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8114:8080
    mem_limit: 512m

  web:
    container_name: invoice_web
    depends_on:
      - db
    image: ezazulhaq02/haa-enterprises:invoice_generator_1.0
    restart: always
    environment:
      spring_datasource_url: jdbc:mysql://invoice_db/hb_invoice_db
    ports:
      - 8105:8104
    mem_limit: 1024m

volumes:
  mysql-invoice-mvc:
